server:
  port: 8081
env.name: dev #dev:开发环境-test:测试环境-pro:生产环境

spring:
  datasource:
      url: jdbc:mysql://10.118.191.56:3306/promotion?characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
